title: Anyi_2025
description: "Class of 2025"
owner_name: Anyi Wang
github_username: Annie0523
github_repo: "Anyi_2025"
baseurl: "/Anyi_2025"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders" }
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" }
# Uncomment one of the following lines if you want to use a different theme:
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - README4YML.md
  - navigation/music.md
  - navigation/notes.md
  - navigation/game.md

